logger:
  enableStackTrace: false

database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  dbName: "go"
  user: "go"
  password: "go"
  sslMode: "disable"
  maxOpenConnections: 10
  maxLifeTimeConnection: 1
  maxIdleConnections: 10
  maxIdleTimeConnection: 1

cache:
  driver: "redis"
  scheme: "tcp"
  host: "localhost"
  port: 6379
  database: 1